<?php

require_once("classes/Viagem.php");
require_once("classes/Contacto.php");
require_once("classes/Banner.php");

// Configurações
$config = [
  "total_caracteres" => 50,
];



// Simulação de Base de Dados
$viagens = [
  new Viagem("Lisboa", "public/imagens/lisboa.jpg", "<p> Lorem ipsum dolor sit amet <mark>consectetur adipisicing elit.</mark> Eius aliquam nulla assumenda soluta deleniti est voluptas, libero quos ullam error tempora nisi numquam earum saepe iusto explicabo esse inventore hic! Lorem ipsum <b>dolor sit amet consectetur adipisicing elit.</b> Eius aliquam nulla assumenda soluta deleniti est voluptas, libero quos ullam error tempora nisi numquam earum saepe iusto explicabo esse inventore hic! Lorem ipsum <a href='https://google.com'>dolor sit amet consectetur adipisicing elit.</a> Eius aliquam nulla assumenda soluta deleniti est voluptas, libero quos ullam error tempora nisi numquam earum saepe iusto explicabo esse inventore hic! </p> <p> Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aliquam nulla assumenda soluta deleniti est voluptas, libero quos ullam error tempora nisi numquam earum saepe iusto explicabo esse inventore hic! Lorem ipsum dolor <u>sit amet consectetur adipisicing elit. Eius aliquam nulla assumenda</u> soluta deleniti est voluptas, libero quos ullam error tempora nisi numquam earum saepe iusto explicabo esse inventore hic! Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aliquam nulla assumenda soluta deleniti est voluptas, libero quos ullam error tempora nisi numquam earum saepe iusto explicabo esse inventore hic! </p> <p> Lorem ipsum dolor sit <mark>amet consectetur adipisicing elit. Eius aliquam nulla assumenda soluta</mark> deleniti est voluptas, libero quos ullam error tempora nisi numquam earum saepe iusto explicabo esse inventore hic! Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aliquam nulla assumenda soluta deleniti est voluptas, libero quos ullam error tempora nisi numquam earum saepe iusto explicabo esse inventore hic! Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aliquam nulla assumenda soluta deleniti est voluptas, libero quos ullam error tempora nisi numquam earum saepe iusto explicabo esse inventore hic! </p>"),
  new Viagem("Porto", "public/imagens/porto.webp", "<p> Lorem ipsum dolor sit amet <i>consectetur adipisicing elit.</i> Eius aliquam nulla assumenda soluta deleniti est voluptas, libero quos ullam error tempora nisi numquam earum saepe iusto explicabo esse inventore hic! Lorem ipsum <b>dolor sit amet consectetur adipisicing elit.</b> Eius aliquam nulla assumenda soluta deleniti est voluptas, libero quos ullam error tempora nisi numquam earum saepe iusto explicabo esse inventore hic! Lorem ipsum <a href='https://google.com'>dolor sit amet consectetur adipisicing elit.</a> Eius aliquam nulla assumenda soluta deleniti est voluptas, libero quos ullam error tempora nisi numquam earum saepe iusto explicabo esse inventore hic! </p> <p> Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aliquam nulla assumenda soluta deleniti est voluptas, libero quos ullam error tempora nisi numquam earum saepe iusto explicabo esse inventore hic! Lorem ipsum dolor <u>sit amet consectetur adipisicing elit. Eius aliquam nulla assumenda</u> soluta deleniti est voluptas, libero quos ullam error tempora nisi numquam earum saepe iusto explicabo esse inventore hic! Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aliquam nulla assumenda soluta deleniti est voluptas, libero quos ullam error tempora nisi numquam earum saepe iusto explicabo esse inventore hic! </p> <p> Lorem ipsum dolor sit <mark>amet consectetur adipisicing elit. Eius aliquam nulla assumenda soluta</mark> deleniti est voluptas, libero quos ullam error tempora nisi numquam earum saepe iusto explicabo esse inventore hic! Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aliquam nulla assumenda soluta deleniti est voluptas, libero quos ullam error tempora nisi numquam earum saepe iusto explicabo esse inventore hic! Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aliquam nulla assumenda soluta deleniti est voluptas, libero quos ullam error tempora nisi numquam earum saepe iusto explicabo esse inventore hic! </p>"),
  new Viagem("Serra da Estrela", "public/imagens/serra.jpg", "<p> Lorem ipsum dolor sit amet <i>consectetur adipisicing elit.</i> Eius aliquam nulla assumenda soluta deleniti est voluptas, libero quos ullam error tempora nisi numquam earum saepe iusto explicabo esse inventore hic! Lorem ipsum <b>dolor sit amet consectetur adipisicing elit.</b> Eius aliquam nulla assumenda soluta deleniti est voluptas, libero quos ullam error tempora nisi numquam earum saepe iusto explicabo esse inventore hic! Lorem ipsum <a href='https://google.com'>dolor sit amet consectetur adipisicing elit.</a> Eius aliquam nulla assumenda soluta deleniti est voluptas, libero quos ullam error tempora nisi numquam earum saepe iusto explicabo esse inventore hic! </p> <p> Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aliquam nulla assumenda soluta deleniti est voluptas, libero quos ullam error tempora nisi numquam earum saepe iusto explicabo esse inventore hic! Lorem ipsum dolor <u>sit amet consectetur adipisicing elit. Eius aliquam nulla assumenda</u> soluta deleniti est voluptas, libero quos ullam error tempora nisi numquam earum saepe iusto explicabo esse inventore hic! Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aliquam nulla assumenda soluta deleniti est voluptas, libero quos ullam error tempora nisi numquam earum saepe iusto explicabo esse inventore hic! </p> <p> Lorem ipsum dolor sit <mark>amet consectetur adipisicing elit. Eius aliquam nulla assumenda soluta</mark> deleniti est voluptas, libero quos ullam error tempora nisi numquam earum saepe iusto explicabo esse inventore hic! Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aliquam nulla assumenda soluta deleniti est voluptas, libero quos ullam error tempora nisi numquam earum saepe iusto explicabo esse inventore hic! Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius aliquam nulla assumenda soluta deleniti est voluptas, libero quos ullam error tempora nisi numquam earum saepe iusto explicabo esse inventore hic! </p>"),
];

$contacto = new Contacto("Rua Qualquer Coisa, 777, Lisboa", "333 444 555", "viagens_pt@email.pt");

$carousel = [
  new Banner("public/imagens/paisagem_1.avif"),
  new Banner("public/imagens/paisagem_2.avif"),
  new Banner("public/imagens/paisagem_3.avif"),
  new Banner("public/imagens/paisagem_4.avif"),
  new Banner("public/imagens/paisagem_5.avif"),
];

?>